Initial v1 docs
buape/kiai-docs pull request #15
Opened 2023-05-02 02:46 UTC by thewilloftheshadow

Closes #11 

Closes KDOCS-3
Closes KDOCS-10
Closes KDOCS-11
Closes KDOCS-12

2023-05-02 18:38 UTC, daksh-gg reviewed
very nice 👍

2023-05-02 21:37 UTC, net-tech requested changes

2023-05-02 21:37 UTC, net-tech commented on pages/_meta.json
Can you add a link to the main website?

2023-05-02 21:37 UTC, net-tech commented on pages/commands/debug.mdx
> +# Ping Command
```suggestion
# Debug Command
```

2023-05-02 21:37 UTC, net-tech commented on pages/commands/debug.mdx
> +-   The Bot's Shard Information
```suggestion
-   Server Information such as the server ID, the bot's permissions, and the server's settings
-   Information about you, such as your Discord ID, permissions in the server, and level
-   General bot information such as the ping and version
```

2023-05-02 21:37 UTC, net-tech commented on pages/commands/leaderboard.mdx
> +This command is available to anyone.
```suggestion
This command is available to everyone.
```

2023-05-02 21:37 UTC, net-tech commented on pages/commands/leaderboard.mdx
> +The `/leaderboard` command will send the top 10 members with the most XP in the server, and provide a link to the full leaderboard located at https://kiai.wtf
```suggestion
The `/leaderboard` command will show the top 10 members with the most XP in the server, and provide a link to the full leaderboard located at https://kiai.wtf.
```

2023-05-02 21:37 UTC, net-tech commented on pages/commands/level-up.mdx
> +| `{user.mention}`       | The user who leveled up  | `@User#0001`                                                                               |
```suggestion
| `{user.mention}`       | A @mention of the user who leveled up  | `@User#0001`                                                                               |
```

2023-05-02 21:37 UTC, net-tech commented on pages/commands/level-up.mdx
> +| `{user.id}`            | The user's ID            | `123456789012345678`                                                                       |
```suggestion
| `{user.id}`            | The user's Discord ID            | `123456789012345678`                                                                       |
```

2023-05-02 21:37 UTC, net-tech commented on pages/commands/level-up.mdx
> +| `{guild.icon}`         | The guild's icon         | `https://cdn.discordapp.com/icons/123456789012345678/abcdef1234567890abcdef1234567890.png` |
```suggestion
| `{guild.id}`           | The server's ID           | `123456789012345678`                                                                       |
| `{guild.name}`         | The server's name         | `My Server`                                                                                |
| `{guild.icon}`         | The server's icon         | `https://cdn.discordapp.com/icons/123456789012345678/abcdef1234567890abcdef1234567890.png` |
```

2023-05-02 21:37 UTC, net-tech commented on pages/commands/ping.mdx
> +The `/ping` command displays the current connection speed of the bot to Discord.
```suggestion
The `/ping` command displays the latency between the bot and Discord.
```

2023-05-02 21:37 UTC, net-tech commented on pages/commands/rank.mdx
> +</Callout>
```suggestion
<Callout type="info" emoji="ℹ️">
	We're still working on the design for our rank card, the current message is
	just a placeholder.
</Callout>
```

2023-05-02 21:37 UTC, net-tech commented on pages/features/kiai.wtf.mdx
> +where 608098293498511360 is the ID of the guild you are viewing the leaderboard for.
```suggestion
where 608098293498511360 is the ID of the server you are viewing the leaderboard for.
```

2023-05-02 23:12 UTC, net-tech approved these changes
Make the change I commented, making as approved because im going to sleep

2023-05-02 23:12 UTC, net-tech commented on pages/_meta.json
> +		"title": "Main Site",
```suggestion
		"title": "Website",
```

2023-05-03 00:15 UTC, thewilloftheshadow commented
Two approvals outside of Github's system

2023-05-03 00:16 UTC, merged